<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5LiW55WM');
$cfg_Cs[4]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(3,1,1,'5b+G55m957O757G7');
$cfg_Cs[7]=array(3,1,1,'5YWz5Lqo57O75YiX');
$cfg_Cs[8]=array(3,1,1,'5pW05pyo5a6a5Yi2');
$cfg_Cs[9]=array(3,1,1,'576O5a2m5pyo5L2c');
$cfg_Cs[10]=array(3,1,1,'5a625bGF57O75YiX');
$cfg_Cs[11]=array(3,1,1,'5LqU6YeR57O75YiX');
$cfg_Cs[12]=array(0,1,1,'5pCc57Si');
?>