<?php
$z[0]=Array("pubdate","",190,236);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",285,331);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%b\",@me)";
$z[2]=Array("pubdate","",380,426);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("litpic","",524,539);
$z[3][4]=array();
$z[4]=Array("title","",582,596);
$z[4][4]=array();

?>