<?php
$z[0]=Array("typeurl","",47,63);
$z[0][4]=array();
$z[1]=Array("global","",128,161);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",298,314);
$z[2][4]=array();
$z[3]=Array("typename","",350,367);
$z[3][4]=array();
$z[4]=Array("typeurl","",419,435);
$z[4][4]=array();
$z[5]=Array("typeimg","",507,523);
$z[5][4]=array();
$z[6]=Array("typename","",561,578);
$z[6][4]=array();

?>