<?php
$z[0]=Array("typeurl","",49,65);
$z[0][4]=array();
$z[1]=Array("global","",132,165);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",306,322);
$z[2][4]=array();
$z[3]=Array("typename","",360,377);
$z[3][4]=array();
$z[4]=Array("typeurl","",433,449);
$z[4][4]=array();
$z[5]=Array("typeimg","",525,541);
$z[5][4]=array();
$z[6]=Array("typename","",581,598);
$z[6][4]=array();

?>