<?php
$z[0]=Array("pubdate","",190,236);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b\",@me)";
$z[1]=Array("pubdate","",282,328);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%d\",@me)";
$z[2]=Array("pubdate","",374,420);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%Y\",@me)";
$z[3]=Array("litpic","",518,533);
$z[3][4]=array();
$z[4]=Array("title","",576,590);
$z[4][4]=array();

?>