<div class="col-md-6">
                  <a href="[field:arcurl/]">
                    <div class="bg_img">
                      <img src="[field:litpic/]" width="100%">

                      <div class="hover-box" style="top: 0%; width: 0%; left: 0px;"></div>
                      <span class="shiz">
                        <span class="heng" style="top: 50%; width: 0px; left: 0%;"></span>
                        <span class="shu" style="left: 50%; height: 0px; top: 0%;"></span>
                      </span>
                    </div>
                  </a>

                  <a href="[field:arcurl/]" class="porod1_b3_b">
                    [field:title/]
                    <span>+</span>
                  </a>
                </div>