<div class="swiper-slide  hlp swiper-slide-duplicate">
              <a href="[field:arcurl/]">
                <div class="bg_img">
                  <img src="[field:litpic/]" width="100%"></div>
                <div class="hover-box" style="left: 0px;"></div>
                <span class="shiz">
                  <span class="heng"></span>
                  <span class="shu"></span>
                </span>
              </a>

              <a href="[field:arcurl/]" class="porod1_b3_b">
                [field:title/]
                <span>+</span>
              </a>
            </div>