<div class="news_center">
  <div class="newsleft">
    <span>[field:pubdatefunction='strftime("%b%d,%Y",@me)'/]</span>
    <p>[field:pubdatefunction='strftime("%d",@me)'/]</p>
    <span>[field:pubdatefunction='strftime("%Y",@me)'/]</span>
  </div>
  <a href="[field:arcurl/]">
    <div class="news_img">
      <img src="[field:litpic/]" class="newscent" width="100%" />
      <span>
        <img src="[field:global.cfg_templets_skin/]/images/arrow-left-white.png"></span>
    </div>
  </a>
  <a href="[field:arcurl/]">
    <div class="newsright">
      <h4>[field:title/]</h4>
      <p class="hidden-xs hidden-sm">
        [field:description/]...
      </p>
    </div>
  </a>
</div>