<?php
$z[0]=Array("pubdate","",63,116);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[1]=Array("pubdatefunction='strftime("%d",@me)'","",133,178);
$z[1][4]=array();
$z[2]=Array("pubdatefunction='strftime("%y",@me)'","",194,239);
$z[2][4]=array();
$z[3]=Array("arcurl","",269,284);
$z[3][4]=array();
$z[4]=Array("litpic","",332,347);
$z[4][4]=array();
$z[5]=Array("global","",415,448);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("arcurl","",518,533);
$z[6][4]=array();
$z[7]=Array("title","",576,590);
$z[7][4]=array();
$z[8]=Array("description","",644,664);
$z[8][4]=array();

?>