<div class="mumen_sec_con mumen_sec_con1 visible-xs visible-sm">
        <div class="row clm">
          <div class="col-sm-6 clp ">
            <div class="mumen_sec_con_img mumen_sec_con_img1" style="background: url([field:litpic/]) center no-repeat; background-size: cover;"></div>
          </div>
        </div>
      </div>
      <div class="mumen_sec_con mumen_sec_con1">
        <div class="row clm">
          <div class="col-sm-6 clp">
            <div class="mumen_sec_con_zi">
              <h5>[field:title/]</h5>
              <p>[field:body/]</p>
            </div>
          </div>
          <div class="col-sm-6 clp hidden-xs hidden-sm">
            <div class="mumen_sec_con_img mumen_sec_con_img1" style="background: url([field:litpic/]) center no-repeat; background-size: cover;"></div>
          </div>
        </div>
      </div>