<?php
$z[0]=Array("typeurl","",49,65);
$z[0][4]=array();
$z[1]=Array("global","",116,149);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",286,302);
$z[2][4]=array();
$z[3]=Array("title","",338,352);
$z[3][4]=array();
$z[4]=Array("typeurl","",404,420);
$z[4][4]=array();
$z[5]=Array("typeimg","",472,488);
$z[5][4]=array();
$z[6]=Array("title","",524,538);
$z[6][4]=array();

?>