<?php
$z[0]=Array("pubdate","",64,117);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b %d, %Y\",@me)";
$z[1]=Array("pubdatefunction='strftime("%d",@me)'","",136,181);
$z[1][4]=array();
$z[2]=Array("pubdatefunction='strftime("%y",@me)'","",197,242);
$z[2][4]=array();
$z[3]=Array("arcurl","",272,287);
$z[3][4]=array();
$z[4]=Array("litpic","",335,350);
$z[4][4]=array();
$z[5]=Array("global","",418,451);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("arcurl","",521,536);
$z[6][4]=array();
$z[7]=Array("title","",579,593);
$z[7][4]=array();
$z[8]=Array("description","",647,667);
$z[8][4]=array();

?>