<?php
$z[0]=Array("pubdate","",198,244);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%Y\",@me)";
$z[1]=Array("pubdate","",295,341);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%m\",@me)";
$z[2]=Array("pubdate","",392,438);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%d\",@me)";
$z[3]=Array("litpic","",542,557);
$z[3][4]=array();
$z[4]=Array("title","",602,616);
$z[4][4]=array();

?>