<div class="news_center">
  <div class="newsleft">
    <span>March</span>
    <p>16</p>
    <span>2018</span>
  </div>
  <a href="[field:arcurl/]">
    <div class="news_img">
      <img src="[field:litpic/]" class="newscent" width="100%" />
      <span>
        <img src="/templates/ghdoor/images/arrow-left-white.png"></span>
    </div>
  </a>
  <a href="[field:arcurl/]">
    <div class="newsright">
      <h4>[field:title/]</h4>
      <p class="hidden-xs hidden-sm">
        [field:description/]...
      </p>
    </div>
  </a>
</div>