<a href="[field:typeurl/]">
             <div class="pro_r">
               <h3>[field:typename/]</h3>
               {dede:sql sql='Select description from dede_arctype where id=6'}
             [field:description/]
                {/dede:sql}
             </div>
           </a>
         </div>
		
		 
       </div>  
       </div>
	   
	   
	   <div class="prod_box visible-xs visible-sm">
       <div class="row clm">
         
         <div class="col-md-6 clp">
            <a href="[field:typeurl/]"><div class="pro_r">
            <h3>忆白系列</h3>
              <p>元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。</p>
              <p>
                公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
               </p>            </div></a>
         </div>
		 
       </div>  
       </div>
	   		<div class="prod_box visible-xs visible-sm">    
       <div class="row clm">   
	   
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner1.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081600.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081607.png" width="150">
                <h3>关亨系列</h3>
              </div>
             <a href="http://ghdoor.com/product_inner1.html"> <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081618.png" width="150">
                <h3>关亨系列</h3>
               </div></a>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>
	   <div class="prod_box">    
       <div class="row clm">    
	   
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner1.html"><div class="pro_r">
            <h3>关亨系列</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner1.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081600.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081607.png" width="150">
                <h3>关亨系列</h3>
              </div>
              <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081618.png" width="150">
                <h3>关亨系列</h3>
              </div>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>  	
		       <div class="prod_box">
       <div class="row clm">
		
	    
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner2.html"><div class="pro_l pro_l2" 
			style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081717.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081729.png" width="150">
                <h3>整木定制</h3>
              </div>
              <a href="http://ghdoor.com/product_inner2.html"><div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081732.png" width="150">
                <h3>整木定制</h3>
              </div></a>
            </div></a>
         </div>
         
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner2.html"><div class="pro_r">
            <h3>整木定制</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		
		 
       </div>  
       </div>
	   
	   
	   <div class="prod_box visible-xs visible-sm">
       <div class="row clm">
         
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner2.html"><div class="pro_r">
            <h3>整木定制</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		 
       </div>  
       </div>
	   		<div class="prod_box visible-xs visible-sm">    
       <div class="row clm">   
	   
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner3.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081745.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081749.png" width="150">
                <h3>美学木作</h3>
              </div>
             <a href="http://ghdoor.com/product_inner3.html"> <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081752.png" width="150">
                <h3>美学木作</h3>
               </div></a>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>
	   <div class="prod_box">    
       <div class="row clm">    
	   
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner3.html"><div class="pro_r">
            <h3>美学木作</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner3.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081745.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081749.png" width="150">
                <h3>美学木作</h3>
              </div>
              <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081752.png" width="150">
                <h3>美学木作</h3>
              </div>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>  	
		       <div class="prod_box">
       <div class="row clm">
		
	    
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner4.html"><div class="pro_l pro_l2" 
			style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081847.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081854.png" width="150">
                <h3>家具系列</h3>
              </div>
              <a href="http://ghdoor.com/product_inner4.html"><div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081857.png" width="150">
                <h3>家具系列</h3>
              </div></a>
            </div></a>
         </div>
         
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner4.html"><div class="pro_r">
            <h3>家具系列</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		
		 
       </div>  
       </div>
	   
	   
	   <div class="prod_box visible-xs visible-sm">
       <div class="row clm">
         
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner4.html"><div class="pro_r">
            <h3>家具系列</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		 
       </div>  
       </div>
	   		<div class="prod_box visible-xs visible-sm">    
       <div class="row clm">   
	   
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner5.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081916.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081920.png" width="150">
                <h3>五金系列</h3>
              </div>
             <a href="http://ghdoor.com/product_inner5.html"> <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081922.png" width="150">
                <h3>五金系列</h3>
               </div></a>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>
	   <div class="prod_box">    
       <div class="row clm">    
	   
         <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner5.html"><div class="pro_r">
            <h3>五金系列</h3>
              <p>
	元1642~1646年，著名建筑设计师佛兰苏瓦.曼萨尔在法国巴黎近郊，
                设计建造了拉斐特城堡（Maisons Laffitte),被誉为十大贵族城堡之一，
                成为当时法国巴洛克建筑的代表作。
</p>
<p>
	公元21世纪，拉斐特城堡的设计图纸作为中法文化交流作品。
                在中国木门之都的南浔，关亨艺墅家得以完美展现，成为新木艺装饰的心标杆。
                轻奢美学、精致雕花、柔美撞色，金银绽放等艺术工艺的奢华再现，
                散发出古老欧洲皇家贵族的神韵。
</p>            </div></a>
         </div>
		 <div class="col-md-6 clp">
            <a href="http://ghdoor.com/product_inner5.html"><div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081916.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081920.png" width="150">
                <h3>五金系列</h3>
              </div>
              <div class="pro_con1">
                <img src="[field:global.cfg_templets_skin/]/images/unohacha_20161025081922.png" width="150">
                <h3>五金系列</h3>
              </div>
            </div></a>
         </div>
	   </div>	 
       </div>
	   </div>  	
		   
      
		 
		 
       	 
       </div>
	   	   	   	   	    
    </div> 
    </div> 


<!--  / ab_sec1  --> 








</div>
<!--  / warpper  --> 
  {dede:include filename="footer.html"