<?php
$z[0]=Array("typeurl","",50,66);
$z[0][4]=array();
$z[1]=Array("global","",134,167);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",310,326);
$z[2][4]=array();
$z[3]=Array("typename","",378,395);
$z[3][4]=array();
$z[4]=Array("typeurl","",453,469);
$z[4][4]=array();
$z[5]=Array("typeimg","",547,563);
$z[5][4]=array();
$z[6]=Array("typename","",617,634);
$z[6][4]=array();

?>