<?php
$z[0]=Array("typeurl","",49,65);
$z[0][4]=array();
$z[1]=Array("cfg_templets_skin","/images/unohacha_20161025080846.jpg) no-repeat;background-size: cover;\">\r\n              <div class=\"pro_con\">\r\n                <img src=\"http://ghdoor.com/upload/unohacha_20161025081047.png\" width=\"150\">\r\n                <h3>忆白系列</h3>\r\n              </div>\r\n              <a href=\"[field:typeurl",116,446);
$z[1][4]=array();

?>