<div class="col-md-6 clp">
            <a href="[field:typeurl/]"><div class="pro_l pro_l2" style="background: url([field:cfg_templets_skin]/images/unohacha_20161025080846.jpg) no-repeat;background-size: cover;">
              <div class="pro_con">
                <img src="http://ghdoor.com/upload/unohacha_20161025081047.png" width="150">
                <h3>忆白系列</h3>
              </div>
              <a href="[field:typeurl/]"><div class="pro_con1">
                <img src="http://ghdoor.com/upload/unohacha_20161025081050.png" width="150">
                <h3>忆白系列</h3>
              </div></a>
            </div></a>
         </div>