<div class="col-md-3 col-xs-12">
            <div class="new_d">
              <a href="http://ghdoor.com/news_inner_18.html">
                <p>
                  <span>[field:pubdate function='strftime("%b",@me)'/]</span>
                  <p>[field:pubdate function='strftime("%d",@me)'/]</p>
                  <span>[field:pubdate function='strftime("%Y",@me)'/]</span>
                </p>
                <div class="new_img">
                  <img src="[field:litpic/]" width="100%"></div>
                <h3>[field:title/]</h3>
            </a>
            </div>
          </div>