<?php
$z[0]=Array("pubdate","",175,221);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%b\",@me)";
$z[1]=Array("pubdate","",251,297);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%d\",@me)";
$z[2]=Array("pubdate","",327,373);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%Y\",@me)";
$z[3]=Array("litpic","",471,486);
$z[3][4]=array();
$z[4]=Array("title","",529,543);
$z[4][4]=array();

?>