<div class="col-md-6 clp">
              <a href="[field:typeurl/]">
                <div class="pro_l pro_l2" style="background: url([field:global.cfg_templets_skin/]/images/unohacha_20161025081600.jpg) no-repeat;background-size: cover;">
                  <div class="pro_con">
                    <img src="[field:typeimg/]" width="150">
                    <h3>[field:typename/]</h3>
                  </div>
                  <a href="[field:typeurl/]">
                    <div class="pro_con1">
                      <img src="[field:typeimg/]" width="150">
                      <h3>[field:typename/]</h3>
                    </div>
                  </a>
                </div>
              </a>
            </div>