<?php
$z[0]=Array("typeurl","",51,67);
$z[0][4]=array();
$z[1]=Array("global","",136,169);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",314,330);
$z[2][4]=array();
$z[3]=Array("typename","",370,387);
$z[3][4]=array();
$z[4]=Array("typeurl","",447,463);
$z[4][4]=array();
$z[5]=Array("typeimg","",543,559);
$z[5][4]=array();
$z[6]=Array("typename","",601,618);
$z[6][4]=array();

?>