<?php
$z[0]=Array("typeurl","",49,65);
$z[0][4]=array();
$z[1]=Array("global","",116,149);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",286,302);
$z[2][4]=array();
$z[3]=Array("typename","",338,355);
$z[3][4]=array();
$z[4]=Array("typeurl","",407,423);
$z[4][4]=array();
$z[5]=Array("typeimg","",475,491);
$z[5][4]=array();
$z[6]=Array("typename","",527,544);
$z[6][4]=array();

?>