<?php
$z[0]=Array("typeurl","",48,64);
$z[0][4]=array();
$z[1]=Array("global","",130,163);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("typeimg","",302,318);
$z[2][4]=array();
$z[3]=Array("typename","",359,376);
$z[3][4]=array();
$z[4]=Array("typeurl","",430,446);
$z[4][4]=array();
$z[5]=Array("typeimg","",520,536);
$z[5][4]=array();
$z[6]=Array("typename","",579,596);
$z[6][4]=array();

?>